-- for debugging
-- select adnl.position as list_position,adnl.notification_list_id,nlnm.position as method_position,nlnm.notification_method_id,nm.contact_id, nc.name, nm.type, nm.data, nlnm.delay
--
-- --select nc.name, nm.type, nm.data, nlnm.delay
-- from alarm_definitions_notification_lists adnl
-- join notification_lists_notification_methods nlnm on (adnl.notification_list_id=nlnm.notification_list_id)
-- join notification_methods nm on (nlnm.notification_method_id=nm.notification_method_id)
-- join notification_contacts nc on (nm.contact_id=nc.contact_id)
-- where alarm_definition_id = 1101
-- order by adnl.position asc, nlnm.position;

-- select operator_id, priority, description,
--    short_message,full_message
-- from alarm_definitions
-- where alarm_definition_id = 1101;
